### ISSUE TITLE
Bug sometimes prevents saving

### ISSUE THREAD

**Issue by Nudin** [Nudin/makesense#16]
```
ERROR:uwsgi_file__data_project_machtsinn_www_python_src_app:Exception on /save [POST]
Traceback (most recent call last):
  File "/data/project/machtsinn/www/python/venv/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/project/machtsinn/www/python/venv/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/project/machtsinn/www/python/venv/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/project/machtsinn/www/python/venv/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/data/project/machtsinn/www/python/venv/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/project/machtsinn/www/python/venv/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/project/machtsinn/www/python/src/app.py", line 183, in save
    claims = sense.claims().get("P5137")
  File "/data/project/machtsinn/www/python/venv/lib/python3.5/site-packages/LexData/__init__.py", line 272, in claims
    return {k: [Claim(c) for c in v] for k, v in self["claims"].items()}
AttributeError: 'list' object has no attribute 'items'
```

**Comment by Nudin** [comment]
Should be already fixed in LexData, now updated LexData to 0.1.8 – should solve this.
